import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";
import 'react-tooltip/dist/react-tooltip.css'
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import Sidebar from "@/components/Sidebar";
import { Toaster } from "@/components/ui/toaster"
import { SidebarProvider } from "@/context/SidebarContext";
import MainContent from "@/components/MainContent";
import { UserAuthProvider } from "@/context/UserAuthContext";
import '@/config/index'
import { StoreProvider as NextReduxProvider } from "./StoreProvider";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const dynamic = 'force-dynamic'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased",
        fontSans.variable
      )}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            <NextReduxProvider>
              <UserAuthProvider>
                <Sidebar />
                <MainContent>{children}</MainContent>
                <Toaster />
              </UserAuthProvider>
            </NextReduxProvider>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
